# Generated by Django 4.0.6 on 2022-07-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inicio',
            name='button',
            field=models.CharField(max_length=150, verbose_name='Nome do botão'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='link',
            field=models.CharField(max_length=150, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='titulo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titulo'),
        ),
    ]
